### ISSUE TITLE
markdown: redpen crashes on image nested in link

### ISSUE THREAD

**Issue by rhysd** [redpen-cc/redpen#574]
### Repro

- test.md

```markdown
[![ラベル](https://example.com/path/to/img.png)](https://example.com/path/to/link)
```

- command

```
$ redpen test.md
```

- error

```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(ArrayList.java:418)
	at java.util.ArrayList.get(ArrayList.java:431)
	at cc.redpen.parser.markdown.ToFileContentSerializer.visit(ToFileContentSerializer.java:239)
	at org.pegdown.ast.ExpLinkNode.accept(ExpLinkNode.java:33)
	at cc.redpen.parser.markdown.ToFileContentSerializer.visitChildren(ToFileContentSerializer.java:73)
	at cc.redpen.parser.markdown.ToFileContentSerializer.visit(ToFileContentSerializer.java:444)
	at org.pegdown.ast.SuperNode.accept(SuperNode.java:43)
	at cc.redpen.parser.markdown.ToFileContentSerializer.visitChildren(ToFileContentSerializer.java:73)
	at cc.redpen.parser.markdown.ToFileContentSerializer.visit(ToFileContentSerializer.java:289)
	at org.pegdown.ast.ParaNode.accept(ParaNode.java:35)
	at cc.redpen.parser.markdown.ToFileContentSerializer.visitChildren(ToFileContentSerializer.java:73)
	at cc.redpen.parser.markdown.ToFileContentSerializer.visit(ToFileContentSerializer.java:304)
	at org.pegdown.ast.RootNode.accept(RootNode.java:51)
	at cc.redpen.parser.markdown.ToFileContentSerializer.toFileContent(ToFileContentSerializer.java:89)
	at cc.redpen.parser.MarkdownParser.parse(MarkdownParser.java:90)
	at cc.redpen.parser.BaseDocumentParser.parse(BaseDocumentParser.java:47)
	at cc.redpen.RedPen.parse(RedPen.java:119)
	at cc.redpen.Main.run(Main.java:169)
	at cc.redpen.Main.main(Main.java:59)
```

### Environment

- OS X 10.11.3
- redpen 1.5.0

-----

I encountered this bug when I tried to check a markdown document including Travis CI build status badge.

**Comment by takahi-i** [comment]
Thank you very much for the report @rhysd! We will  look into the case.

**Comment by takahi-i** [comment]
Hello @rhysd. I merged the hot fix (#575) for the problem. Hopefully the update works for you. I will close this issue. Please let us know when you still have problems. We will create another issue or reopen this.

**Comment by rhysd** [comment]
@takahi-i 

Thank you for the fix.  I'll confirm it at next release :relaxed:

**Comment by takahi-i** [comment]
Released v1.5.3 including the fix.

Would be helpful when you still have the problem :bow: 

https://github.com/redpen-cc/redpen/releases/tag/redpen-1.5.3

**Comment by rhysd** [comment]
Sure.  I confirmed the fix :smile:

**Comment by takahi-i** [comment]
Thank you very much :smile_cat:
