### ISSUE TITLE
#574 is still alive on multiple image links

### ISSUE THREAD

**Issue by rhysd** [redpen-cc/redpen#578]
## Repro

- Code

```markdown
[![ラベル](https://example.com/path/to/img.png)](https://example.com/path/to/link)
[![ラベル2](https://example.com/path/to/img2.png)](https://example.com/path/to/link)
```

- Command

```
$ redpen foo.md
```

- Output

```
[2016-03-27 11:41:12.613][INFO ] cc.redpen.Main - Configuration file: /usr/local/Cellar/redpen/1.5.3/libexec/conf/redpen-conf-ja.xml
[2016-03-27 11:41:12.617][INFO ] cc.redpen.config.ConfigurationLoader - Loading config from specified config file: "/usr/local/Cellar/redpen/1.5.3/libexec/conf/redpen-conf-ja.xml"
[2016-03-27 11:41:12.624][INFO ] cc.redpen.config.ConfigurationLoader - Succeeded to load configuration file
[2016-03-27 11:41:12.624][INFO ] cc.redpen.config.ConfigurationLoader - Language is set to "ja"
[2016-03-27 11:41:12.624][WARN ] cc.redpen.config.ConfigurationLoader - No variant configuration...
[2016-03-27 11:41:12.625][INFO ] cc.redpen.config.ConfigurationLoader - No "symbols" block found in the configuration
[2016-03-27 11:41:12.627][INFO ] cc.redpen.config.SymbolTable - "ja" is specified.
[2016-03-27 11:41:12.627][INFO ] cc.redpen.config.SymbolTable - "zenkaku" variant is specified
[2016-03-27 11:41:12.904][INFO ] cc.redpen.parser.SentenceExtractor - "[。, ？, ！]" are added as a end of sentence characters
[2016-03-27 11:41:12.905][INFO ] cc.redpen.parser.SentenceExtractor - "[’, ”]" are added as a right quotation characters
[2016-03-27 11:41:12.948][INFO ] cc.redpen.util.DictionaryLoader - Succeeded to load katakana word dictionary.
[2016-03-27 11:41:12.949][INFO ] cc.redpen.validator.JavaScriptValidator - JavaScript validators directory: js
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(ArrayList.java:638)
        at java.util.ArrayList.get(ArrayList.java:414)
        at cc.redpen.parser.markdown.MergedCandidateSentence.merge(MergedCandidateSentence.java:59)
        at cc.redpen.parser.markdown.ToFileContentSerializer.createSentenceList(ToFileContentSerializer.java:148)
        at cc.redpen.parser.markdown.ToFileContentSerializer.fixSentence(ToFileContentSerializer.java:101)
        at cc.redpen.parser.markdown.ToFileContentSerializer.visit(ToFileContentSerializer.java:294)
        at org.pegdown.ast.ParaNode.accept(ParaNode.java:35)
        at cc.redpen.parser.markdown.ToFileContentSerializer.visitChildren(ToFileContentSerializer.java:74)
        at cc.redpen.parser.markdown.ToFileContentSerializer.visit(ToFileContentSerializer.java:308)
        at org.pegdown.ast.RootNode.accept(RootNode.java:51)
        at cc.redpen.parser.markdown.ToFileContentSerializer.toFileContent(ToFileContentSerializer.java:90)
        at cc.redpen.parser.MarkdownParser.parse(MarkdownParser.java:85)
        at cc.redpen.parser.BaseDocumentParser.parse(BaseDocumentParser.java:47)
        at cc.redpen.RedPen.parse(RedPen.java:119)
        at cc.redpen.Main.run(Main.java:169)
        at cc.redpen.Main.main(Main.java:59)```
```

## Environment

- redpen 1.5.3
- OS X 10.11.4
- `java -version` : `1.8.0_11-b12`

---

One image link works well after the fix of #574. But multiple images still doesn't work.

**Comment by takahi-i** [comment]
Thank you very much for the report @rhysd! I will reproduce and fix this problem immediately.

**Comment by rhysd** [comment]
Thanks!  I'll confirm the fix at next release.

**Comment by takahi-i** [comment]
Sorry for making you wait. Hopefully the fix works for your environment. I've released the latest version containing the #579. https://github.com/redpen-cc/redpen/releases/tag/redpen-1.5.4 

As for the homebrew, I will submit the pull request soon.

**Comment by takahi-i** [comment]
Sent the pull request to homebrew. https://github.com/Homebrew/homebrew/pull/50532

**Comment by rhysd** [comment]
I confirmed the bug has gone with redpen 1.5.4.  Thanks!

**Comment by takahi-i** [comment]
Thank you very much for the report @rhysd! :tada:
